import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./_components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black `}
      >
        <Navbar/>
        {children}
        <div className="border-t-[2px] flex justify-around  text-white text-sm md:text-xl  p-10">
        <h2>2024 © All Rights Reserved</h2>
        <h2>Crafted with ❤️ by Dev</h2>
      </div>
      </body>
    </html>
  );
}
